
export const Routes = {
  Login: '/login',
  Dashboard: '/',
  Restaurants: '/restaurants',
  RestaurantAdd: '/restaurants/add',
  RestaurantEdit:(id: string) => `/restaurants/edit/${id}`,
  Users: '/users',
  UserAdd: '/users/add',
  UserEdit: (id: string) => `/users/edit/${id}`,
  MenuSectionsAdd: '/menu-sections/add',
  MenuSectionsEdit: (id: string) => `/menu-sections/edit/${id}`,
  ProudctAdd: '/products/add',
  ProudctEdit: (id: string) => `/products/edit/${id}`,
  ScheduleAddOrEdit: '/schedule/add',
  Drivers: '/drivers',
  DriversAdd: '/drivers/add',
  DriversEdit: (id: string) => `/drivers/edit/${id}`,
  Modifiers: '/modifiers',
  ModifiersAdd: '/modifiers/add',
  ModifiersEdit: (id: string) => `/modifiers/edit/${id}`,
};